export const ADD_ARTICLE = "ADD_ARTICLE";
export const FILTER_ARTICLES = "FILTER_ARTICLES";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const SEARCH_TAG = "SEARCH_TAG";
export const REMOVE_SEARCH_TAG = "REMOVE_SEARCH_TAG";
